Fixed init color format
Pisyukaev/twitch-sub-goal pull request #28
Opened 2023-05-23 21:24 UTC by Pisyukaev

Added context for styles
Init styles to the storage and use actual styles for render

2023-05-24 09:59 UTC, crashmax-dev commented on app/hooks/useData.ts
> +  const [styles] = useStorage(STORAGE_KEYS.CUSTOM_STYLES)
тут нужен дженерик для хука

2023-05-24 10:00 UTC, crashmax-dev commented on app/hooks/useFonts.ts
> +  const [selectedFont, setSelectedFont] = useStorage(STORAGE_KEYS.SELECTED_FONT)
дженерик для хука

2023-05-24 10:00 UTC, crashmax-dev commented on app/hooks/useStyles.ts
> +  const [actualStyles, setActualStyles] = useStorage(STORAGE_KEYS.CUSTOM_STYLES)
дженерик для хука

2023-05-24 10:03 UTC, crashmax-dev requested changes
Поправить типы в хуках

2023-05-26 15:50 UTC, crashmax-dev approved these changes
Осталось ли что-нибудь?

2023-05-26 16:07 UTC, Pisyukaev commented
Вроде нет

2023-05-26 16:25 UTC, crashmax-dev commented
> Вроде нет

мерджи

2023-05-26 17:45 UTC, merged